# Generated by Django 3.2.8 on 2022-01-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteShare', '0007_remove_postedquote_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedquote',
            name='comments',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
